[ADD] 구매내역 페이지 API 구현
wecode-bootcamp-korea/38-1st-weKEA-backend pull request #10
Opened 2022-10-24 08:21 UTC by c0zyb1ue

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 구매내역 페이지에 필요한 데이터를 반환하는 API를 구현한다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 구매내역 페이지

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-10-25 02:30 UTC, kyeongraekim requested changes

2022-10-25 02:30 UTC, kyeongraekim commented on api/controllers/pageController.js
> +     const id = req.params.id;
- productId 정도로 정확히 어떤 id임을 나타내는지 변수명을 수정해주세요~

2022-10-25 02:30 UTC, kyeongraekim commented on api/models/orderDao.js
> +        throw error
해당 에러는 Dao가 아닌 Service단에서 처리해주세요~

2022-10-25 02:30 UTC, kyeongraekim commented on api/models/orderDao.js
> +        );
다음의 예시 코드와 같은 내용을 models/enums.js 파일에 생성 및 활용하여, 숫자를 직접 기입하는 하드코딩이 아닌 해당 id값을 치환할 수 있는 글자용어로 수정해주세요.

``` javascript
const orderStatusEnum = Object.freeze({
    CART : 1,
    ORDER : 2,
    DONE : 3
})

module.exports ={
    orderStatusEnum
}

2022-10-25 02:30 UTC, kyeongraekim commented on api/models/orderDao.js
> +        );
enum의 역할과 기능을 잘 소개한 블로그 글 링크를 아래 남겨드립니다.
[링크 바로가기](https://sewonzzang.tistory.com/28)

2022-10-25 02:30 UTC, kyeongraekim commented on api/models/orderDao.js
> +
- 해당 내용은 placeholder, ?물음표 표시를 활용한 내용으로 수정해주세요.
- 인자를 직접 받아 SQL Raw 쿼리문에 넣는 행위는 SQL Injection에 매우 취약한 행동입니다. 
- 다음의 링크에서 SQL Injection에 대해서 한 번 살펴보세요!~ [링크 바로가기](https://www.w3schools.com/sql/sql_injection.asp)

2022-10-25 02:30 UTC, kyeongraekim commented on db/migrations/20221018085449_create_users.sql
> +  phone_number VARCHAR(30) NOT NULL,
API 와 상관없는 내용은 내가 의도한 깃헙 브랜치에 올라오지 않게 유의해주세요~

2022-10-25 05:22 UTC, c0zyb1ue commented on db/migrations/20221018085449_create_users.sql
> +  phone_number VARCHAR(30) NOT NULL,
전에 리뷰 남겨주신 내용중에 phone_number로 camelcase 형식에서 바꾸라고 하셔서 가장 빠르게 merge될 것으로 예상되는 페이지에서 수정한 것입니다.

2022-10-26 02:15 UTC, kyeongraekim requested changes

2022-10-26 02:15 UTC, kyeongraekim commented on api/models/enums.js
> +     cancelOrder : 2
ENUM 상태값은 대게 ADDED, CANCELED 정도로 상태 동사의 형태로 관리하는 편입니다. 해당 내용만 간단히 수정해주세요~

2022-10-26 02:15 UTC, kyeongraekim commented on api/controllers/orderController.js
> +    res.status(200).json({ message : "Successfully_Cancled" });
에러메세지 오타 한 번 신경써주세요!~

2022-10-26 02:15 UTC, kyeongraekim commented on api/models/orderDao.js
> +const checkPoints = async(id) => {
해당 id 값의 의미가 불명확합니다. userId로 확인하는 것 같아 보이는데 매개변수의 명칭도 꼭 언제 어디서든 그 의미가 잘드러나게 설정해주세요~

2022-10-26 02:15 UTC, kyeongraekim commented on api/models/orderDao.js
> +    }
- cart가 order로 넘어가는 순간에 서버가 끊기는 등의 오류가 나면 문제가 생길 수 있습니다. 따라서 한 차례 완벽한 통신이 이루어지지 않는 경우에 다시 초기상태로 RollBack 해서 돌아가는 Transaction의 개념을 적용하여 보다 안전한 전자상거래를 유도해주세요.
- Transaction은 TypeORM에서 다음의 내용처럼 이루어집니다. [링크 바로가기](https://orkhan.gitbook.io/typeorm/docs/transactions)

2022-10-26 08:38 UTC, kyeongraekim approved these changes
LGTM!~

2022-10-26 08:38 UTC, merged