[ADD] main-page API 구현
wecode-bootcamp-korea/38-1st-weKEA-backend pull request #5
Opened 2022-10-19 11:52 UTC by haemong

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 메인 페이지 구성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1.  메인 페이지
- products table에 담겨있는 상품들을 랜덤하게 10개의 제품을 가져와 리턴
- 인증인가를 거치지 않고 들어올 수 있게 구현
- RESTful API 구현
- 자바스크립트의 반복문과 랜덤함수과 INNER JOIN을 활용한 쿼리문 작성

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 처음으로 API를 구현하면서 인증인가가 필요한 페이지인지 어떻게 API 주소를 구성할 것인지 데이터적인 관점에서 어떤 페이지에 어떤 데이터를 보내줘야 하는지 생각해보는 계기가 되었다

<br />

## :: 기타 질문 및 특이 사항
- Dao 에서 작성한 코드를 쿼리문으로만 구현해서 실행할 수 있는지 궁금합니다.

2022-10-21 09:45 UTC, kyeongraekim requested changes

2022-10-21 09:45 UTC, kyeongraekim commented on api/models/mainDao.js
> +                );
- 해당 부분은 product_id 로 동일 조건으로 where 절 필터링을 걸어주고 계신데, 전체 테이블로 join 하여 SQL 선에서 해결하는 방식이 더 효율적으로 보이네요! 
- WHERE IN 절을 써서 배열안의 조건을 필터링 하는 방법을 도전해보세요!~

2022-10-21 09:45 UTC, kyeongraekim commented on api/models/mainDao.js
> +                );
- SQL에 존재하는 order by RANDOM, LIMIT 값의 조합을 잘 섞어서 랜덤으로 섞어서 조합으로 나온 테이블 데이터를 상위 n개 까지 잘라서 전달하는 방법으로 도전해보세요~
- 또한 Image와 관련 된 내용도 sub query 등의 모습이 필요할 수 있겠네요.  다음의 위코드 심화 학습자료 링크를 참고하여서 올바르게 조합에 도전해보세요! [링크 바로가기](https://www.notion.so/wecode/SQL-SQL-Advanced-386ac13ca3034cb1becfa1efe8716606)

2022-10-21 09:45 UTC, kyeongraekim commented on db/migrations/20221018121817_create_users.sql
> +);
conflict 해결해주시고 불필요한 migration 파일들이 올라오지 않게 조치해주세요!~

2022-10-22 01:24 UTC, haemong commented on api/models/mainDao.js
> +                );
어제 git이 좀 꼬여서 우선 수정사항 반영을 못하고 푸쉬했는데 주말에 반영해서 다시 푸쉬하도록 하겠습니다!

2022-10-23 11:21 UTC, c0zyb1ue commented on api/models/mainDao.js
> +                );
보내주신 링크에 초대를 안해주셔서 접속이 불가능합니다. ㅠㅠ

2022-10-25 02:14 UTC, kyeongraekim requested changes

2022-10-25 02:14 UTC, kyeongraekim commented on api/controllers/index.js
> +    mainController
page 기준의 네이밍은 적합하지 않는다는 말씀 다시 한 번 리뷰로 남겨드립니다!~

2022-10-25 02:14 UTC, kyeongraekim commented on api/controllers/mainController.js
> +const randomProducts = catchAsync(async (req, res) => {
함수의 변수명은 동사어구가 꼭 이루어져야 합니다. 어떠한 행위를 정의해야하는지 정확하게 변수명으로 명시해주세요!~

2022-10-25 02:14 UTC, kyeongraekim commented on api/models/mainDao.js
> +        };
해당내용은 다음의 링크를 참고해서 sql 문안에서 또 녹여낼 수는 없을까 고민해보세요!~ https://stackoverflow.com/questions/580639/how-to-randomly-select-rows-in-sql

2022-10-27 06:02 UTC, kyeongraekim requested changes

2022-10-27 06:02 UTC, kyeongraekim commented on api/routes/productRouter.js
> +router.get('', productController.getRandomProducts);
이렇게 엔드포인트를 설정하면 추후 products 로 받을 수 있는 모든 내용을 다 random 내용이 받게 됩니다. 따라서 상세 분기를 이어서 해주세요. localhost:3000/products/random-items 정도가 좋겠네요!~

2022-10-27 06:22 UTC, kyeongraekim approved these changes
LGTM!~

2022-10-27 06:22 UTC, merged