[ADD] 제품상세페이지 API 구현
wecode-bootcamp-korea/38-1st-weKEA-backend pull request #7
Opened 2022-10-22 12:55 UTC by c0zyb1ue

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 제품 상세 페이지에 필요한 데이터를 반환하는 API를 구현한다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
제품 상세 페이지
- 제품 상세 페이지에 필요한 데이터를 각 테이블에서 가져와서 하나의 객체로 합쳐서 반환.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 미리 API documentation을 프론트와 공유한 이후에 API를 구현하니 일의 능률이 올라갔음.

<br />

## :: 기타 질문 및 특이 사항
- 각각의 테이블에서 다른 데이터를 가져와서 models에서 하나의 객체로 합치는 작업까지 했는데 실제로는 Service단에서 합치는게 더 좋을까요?

2022-10-24 03:01 UTC, kyeongraekim requested changes
리뷰내용에 맞게 수정해주시고, 불필요한 파일이 함께 여럿 올라온 것으로 보여집니다~해당 내용 수정해주세요!

2022-10-24 03:01 UTC, kyeongraekim commented on api/controllers/index.js
> +    pageController
- 백엔드는 데이터적 관점에서 사고를 늘 해주셔야합니다. page는 불분명한 변수명들임으로 전체적으로 한 번 수정해주세요!~

2022-10-24 03:01 UTC, kyeongraekim commented on api/models/pageDao.js
> +const productDetail = async(id) => {
- express 함수명은 동사+목적어 형태의 보다 정확한 의미를 명시하는 것이 컨벤션입니다. 따라서 getProductDetailById 정도로 제3의 개발자가 한눈에 보기 편한 변수명으로 수정하여 원활한 협업을 위한 배려를 진행해주세요!~

2022-10-24 03:01 UTC, kyeongraekim commented on api/models/pageDao.js
> +     const productImages = await weKEADataSource.query(`
weKEADatasource의 변수명을 wekeaDataSource Camel Case에 맞게 수정해주시면 좋을 것 같습니다~

2022-10-24 08:55 UTC, c0zyb1ue commented on api/models/pageDao.js
> +     const productImages = await weKEADataSource.query(`
weKEA를 페이지 이름으로 지어서 모든 브랜치에서 weKEA라는 이름을 사용했는데 wekea로 바꿔야하나요?

2022-10-24 09:00 UTC, c0zyb1ue commented on api/controllers/index.js
> +    pageController
page가 붙어있는 이름의 router controller service dao단에서 다른 페이지의 코드들도 합치려고 하는데 그러지 말고 detailPage라고 이름을 변경할까요?

2022-10-25 02:11 UTC, kyeongraekim requested changes

2022-10-25 02:11 UTC, kyeongraekim commented on api/models/pageDao.js
> +     const productImages = await weKEADataSource.query(`
네 변수명은 고유명사처럼 취급하는 것 대신 네이밍 컨벤션을 따르는게 원칙입니다. 더 올바른 데이터소스의 변수명은 appDataSource, mysqlDataSource 등 해당 데이터 소스의 의미론적 명칭을 담는 변수명이 더 좋아보이네요!~

2022-10-25 02:11 UTC, kyeongraekim commented on api/controllers/index.js
> +    pageController
controller의 파일명칭도 product 기준으로 수정해주세요!~

2022-10-25 08:43 UTC, kyeongraekim approved these changes
LGTM!~

2022-10-25 08:43 UTC, merged